version: "3.9"

services:
  postgres:
    image: postgres:13
    restart: unless-stopped
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: appdb
    volumes:
      - ./db_data:/var/lib/postgresql/data
    networks:
      - app-net

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: unless-stopped
    user: "5050:5050"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - ./pgadmin_data:/var/lib/pgadmin
      - ./pgadmin-servers.json:/pgadmin4/servers.json
    ports:
      - "8090:80"
    depends_on:
      - postgres
    networks:
      - app-net

  rabbitmq:
    image: rabbitmq:management
    hostname: finx
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ./rabbitmq_data:/var/lib/rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: myuser
      RABBITMQ_DEFAULT_PASS: mypass
    networks:
      - app-net

  consumer:
    build: ./consumer
    depends_on:
      - rabbitmq
    networks:
      - app-net

  backend:
    build: ./backend
    volumes:
      - ./backend:/app
    depends_on:
      - postgres
      - rabbitmq
    expose:
      - "5000"
    networks:
      - app-net

  frontend:
    build:
      context: ./frontend
      target: prod
    volumes:
      - ./frontend/nginx.conf:/etc/nginx/conf.d/default.conf
    expose:
      - "80"
    networks:
      - app-net

  lb:
    image: nginx:latest
    volumes:
      - ./lb/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend
    networks:
      - app-net


networks:
  app-net:
